inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml
  - .rubocop_todo.yml

# local repo-specific modifications
# ...
#
require:
- rubocop-performance
- rubocop-rails
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'lib/sts/mapper.rb'
    - 'vendor/**/*'
